# -*- coding: utf-8 -*-
# Generated by chutes-ai-manager. Re-run `python cli.py generate ...` after YAML edits.

"""
Auto-generated MusicGen chute (music-gen).
Model: facebook/musicgen-medium
Edit configs/music-gen.yaml and re-run generate.
"""
import io
import uuid
from typing import Optional

# torch/torchaudio are lazy-imported so `chutes build` can load this module without a local GPU stack.
from fastapi import HTTPException
from fastapi.responses import Response
from loguru import logger
from pydantic import BaseModel, Field, field_validator


class MusicGenerationRequest(BaseModel):
    prompt: str = Field(..., min_length=3, max_length=500)
    duration: int = Field(default=10, ge=5, le=30)
    model: str = Field(default="medium")
    guidance_scale: float = Field(default=3.0, ge=1.0, le=10.0)
    seed: Optional[int] = None

    @field_validator("model")
    @classmethod
    def _m(cls, v: str) -> str:
        v = v.lower()
        if v not in ("small", "medium", "large"):
            raise ValueError("model must be small|medium|large")
        return v

    @field_validator("prompt")
    @classmethod
    def _p(cls, v: str) -> str:
        v = v.strip()
        if not v:
            raise ValueError("empty prompt")
        return v


class HealthStatus(BaseModel):
    status: str
    model_loaded: bool
    gpu_available: bool

from chutes.image import Image

image = (
    Image(
        username='sayfpack',
        name='musicgen-chute',
        tag='1.0.0',
        readme='MusicGen text-to-music',
    )
    .from_base('nvidia/cuda:12.1-runtime-ubuntu22.04')
    .set_user("root")
    .run_command('apt-get update && apt-get install -y git curl ffmpeg libsndfile1 && rm -rf /var/lib/apt/lists/*')
    .with_python('3.11')

    .run_command("""
        pip install --no-cache-dir torch torchvision torchaudio \
        --index-url https://download.pytorch.org/whl/cu121
    """)

    .run_command("""
        pip install --no-cache-dir \
        audiocraft>=1.0.0 \
        transformers>=4.30.0 \
        accelerate>=0.20.0 \
        einops>=0.6.0 \
        scipy>=1.10.0 \
        pydantic>=2.0.0 \
        fastapi>=0.100.0 \
        loguru>=0.7.0
    """)
    .with_env('AUDIOCRAFT_CACHE', '/app/models')
    .with_env('HF_HOME', '/app/models')
    .run_command("mkdir -p /app/models")
    .set_workdir("/app")
    .set_user("chutes")
)


from chutes.chute import Chute, NodeSelector

chute = Chute(
    username='sayfpack',
    name='music-gen',
    tagline='AI Music Generation with MusicGen',
    readme='# MusicGen\n\nText-to-music via Meta MusicGen. Edit username and run generate + build.',
    image=image,
    node_selector=NodeSelector(gpu_count=1, min_vram_gb_per_gpu=16, include=['rtx4090', 'rtx3090', 'a100']),
    concurrency=2,
    allow_external_egress=True,
    shutdown_after_seconds=300,
)


MODEL_IDS = {
    "small": "facebook/musicgen-small",
    "medium": "facebook/musicgen-medium",
    "large": "facebook/musicgen-large",
}

DEFAULT_HF_ID = 'facebook/musicgen-medium'


@chute.on_startup()
async def load_model(self):
    import torch
    from audiocraft.models import MusicGen

    self.torch = torch
    self.models = {}
    # Preload: match YAML model.id to small/medium/large when possible, else warm up medium.
    loaded = False
    for k, mid in MODEL_IDS.items():
        if mid == DEFAULT_HF_ID:
            logger.info("Loading MusicGen %s (%s)", k, mid)
            self.models[k] = MusicGen.get_pretrained(mid)
            loaded = True
            break
    if not loaded:
        logger.info("Loading MusicGen medium (%s)", MODEL_IDS["medium"])
        self.models["medium"] = MusicGen.get_pretrained(MODEL_IDS["medium"])
    self.device = "cuda" if torch.cuda.is_available() else "cpu"


@chute.cord(
    public_api_path='/generate',
    public_api_method="POST",
    stream=False,
    output_content_type="audio/wav",
)
async def generate_music(self, data: MusicGenerationRequest) -> Response:
    import torch
    import torchaudio
    from audiocraft.models import MusicGen

    key = data.model
    if key not in self.models:
        mid = MODEL_IDS.get(key)
        if not mid:
            raise HTTPException(status_code=400, detail="Unknown model size")
        self.models[key] = MusicGen.get_pretrained(mid)
    model = self.models[key]
    model.set_generation_params(duration=data.duration, guidance_scale=data.guidance_scale)
    if data.seed is not None:
        torch.manual_seed(data.seed)
    try:
        with torch.no_grad():
            wav = model.generate(descriptions=[data.prompt], progress=False)
        buf = io.BytesIO()
        torchaudio.save(buf, wav[0].cpu(), sample_rate=32000, format="wav")
        buf.seek(0)
        aid = str(uuid.uuid4())[:8]
        return Response(
            content=buf.read(),
            media_type="audio/wav",
            headers={"Content-Disposition": "attachment; filename=musicgen_" + aid + ".wav"},
        )
    except Exception as exc:
        logger.exception("generate failed")
        raise HTTPException(status_code=500, detail=str(exc)) from exc


@chute.cord(
    public_api_path="/health",
    public_api_method="GET",
    output_content_type="application/json",
)
async def health(self) -> HealthStatus:
    import torch

    loaded = bool(getattr(self, "models", None))
    gpu = torch.cuda.is_available()
    st = "healthy" if loaded and gpu else "degraded"
    return HealthStatus(status=st, model_loaded=loaded, gpu_available=gpu)
