# -*- coding: utf-8 -*-
# Generated by chutes-ai-manager. Re-run `python cli.py generate prebuilt-vllm-llama` after YAML edits.

"""
Auto-generated vLLM chute (prebuilt-vllm-llama) — Chutes pre-built image.
HF model: meta-llama/Llama-3.2-3B-Instruct
"""
from chutes.chute import NodeSelector
from chutes.chute.template import build_vllm_chute

chute = build_vllm_chute(
    username="your_username",
    model_name="meta-llama/Llama-3.2-3B-Instruct",
    node_selector=NodeSelector(gpu_count=1, min_vram_gb_per_gpu=16),
    tagline="vLLM — Llama 3.2 3B",
    readme="# vLLM · Meta Llama 3.2 3B\n\nCompact instruct model on Chutes pre-built vLLM image. Ensure HF access if the repo is gated.\n",
    concurrency=48,
    allow_external_egress=False,
    shutdown_after_seconds=300,
    max_instances=1,
    scaling_threshold=0.75,
    engine_args={"max_model_len": 8192, "trust_remote_code": True},
)
