# -*- coding: utf-8 -*-
# Generated by chutes-ai-manager. Re-run `python cli.py generate prebuilt-diffusion-sd15` after YAML edits.

"""
Auto-generated diffusion chute (prebuilt-diffusion-sd15) — Chutes pre-built image.
HF model: runwayml/stable-diffusion-v1-5
"""
from chutes.chute import NodeSelector
from chutes.chute.template.diffusion import build_diffusion_chute

chute = build_diffusion_chute(
    username="your_username",
    name="prebuilt-diffusion-sd15",
    model_name_or_url="runwayml/stable-diffusion-v1-5",
    node_selector=NodeSelector(gpu_count=1, min_vram_gb_per_gpu=16),
    tagline="Diffusion — Stable Diffusion 1.5",
    readme="# SD 1.5 (lighter VRAM)\n\nClassic runwayml SD 1.5 on Chutes pre-built diffusion template.\n",
    concurrency=1,
    shutdown_after_seconds=300,
    max_instances=1,
    scaling_threshold=0.75,
)
