# -*- coding: utf-8 -*-
# Generated by chutes-ai-manager. Re-run `python cli.py generate prebuilt-embedding-large` after YAML edits.

"""
Auto-generated embedding chute (prebuilt-embedding-large) — Chutes pre-built image.
HF model: BAAI/bge-large-en-v1.5
"""
from chutes.chute import NodeSelector
from chutes.chute.template.embedding import build_embedding_chute

chute = build_embedding_chute(
    username="your_username",
    model_name="BAAI/bge-large-en-v1.5",
    node_selector=NodeSelector(gpu_count=1, min_vram_gb_per_gpu=16),
    tagline="Embeddings — BGE Large",
    readme="# BGE Large English v1.5\n\nHeavier embedding model than the small starter; more VRAM, richer vectors.\n",
    concurrency=24,
    allow_external_egress=False,
    shutdown_after_seconds=300,
    max_instances=1,
    scaling_threshold=0.75,
    pooling_type="auto",
    max_embed_len=3072000,
    enable_chunked_processing=True,
)
