# -*- coding: utf-8 -*-
# Generated by chutes-ai-manager. Re-run `python cli.py generate prebuilt-diffusion-flux` after YAML edits.

"""
Auto-generated diffusion chute (prebuilt-diffusion-flux) — Chutes pre-built image.
HF model: black-forest-labs/FLUX.1-dev
"""
from chutes.chute import NodeSelector
from chutes.chute.template.diffusion import build_diffusion_chute

chute = build_diffusion_chute(
    username="your_username",
    name="prebuilt-diffusion-flux",
    model_name_or_url="black-forest-labs/FLUX.1-dev",
    node_selector=NodeSelector(gpu_count=1, min_vram_gb_per_gpu=48),
    tagline="Diffusion — FLUX.1-dev",
    readme="# FLUX.1-dev (high VRAM)\n\nChutes pre-built diffusion image. Needs a strong GPU — adjust NodeSelector if deploy fails.\n",
    concurrency=1,
    shutdown_after_seconds=300,
    max_instances=1,
    scaling_threshold=0.75,
)
