# -*- coding: utf-8 -*-
# Generated by chutes-ai-manager. Re-run `python cli.py generate prebuilt-diffusion` after YAML edits.

"""
Auto-generated diffusion chute (prebuilt-diffusion) — Chutes pre-built image.
HF model: stabilityai/stable-diffusion-xl-base-1.0
"""
from chutes.chute import NodeSelector
from chutes.chute.template.diffusion import build_diffusion_chute

chute = build_diffusion_chute(
    username="your_username",
    name="prebuilt-diffusion",
    model_name_or_url="stabilityai/stable-diffusion-xl-base-1.0",
    node_selector=NodeSelector(gpu_count=1, min_vram_gb_per_gpu=24),
    tagline="Diffusion — image generation",
    readme="# Diffusion on Chutes (pre-built image)\n\nUses `build_diffusion_chute`. Typical endpoint: `POST /generate`.\nSee https://chutes.ai/docs/guides/templates\n",
    concurrency=1,
    shutdown_after_seconds=300,
    max_instances=1,
    scaling_threshold=0.75,
)
