# -*- coding: utf-8 -*-
# Generated by chutes-ai-manager. Re-run `python cli.py generate ...` after YAML edits.

"""
Auto-generated SGLang chute (prebuilt-sglang) — Chutes pre-built image.
HF model: Qwen/Qwen2.5-7B-Instruct
Edit configs/prebuilt-sglang.yaml and re-run generate.
Docs: https://chutes.ai/docs/sdk-reference/templates
"""
from chutes.chute import NodeSelector
from chutes.chute.template.sglang import build_sglang_chute

chute = build_sglang_chute(
    username="your_username",
    model_name="Qwen/Qwen2.5-7B-Instruct",
    node_selector=NodeSelector(gpu_count=1, min_vram_gb_per_gpu=16),
    tagline="SGLang — structured LLM serving",
    readme="# SGLang on Chutes (pre-built image)\n\nUses `build_sglang_chute`. See https://chutes.ai/docs/guides/templates\n",
    concurrency=32,
    allow_external_egress=False,
    shutdown_after_seconds=300,
    max_instances=1,
    scaling_threshold=0.75,
)
