# -*- coding: utf-8 -*-
# Generated by chutes-ai-manager. Re-run `python cli.py generate prebuilt-sglang-mistral` after YAML edits.

"""
Auto-generated SGLang chute (prebuilt-sglang-mistral) — Chutes pre-built image.
HF model: mistralai/Mistral-7B-Instruct-v0.3
"""
from chutes.chute import NodeSelector
from chutes.chute.template.sglang import build_sglang_chute

chute = build_sglang_chute(
    username="your_username",
    model_name="mistralai/Mistral-7B-Instruct-v0.3",
    node_selector=NodeSelector(gpu_count=1, min_vram_gb_per_gpu=24),
    tagline="SGLang — Mistral 7B",
    readme="# SGLang · Mistral 7B Instruct\n\nSame family as the default vLLM starter, served with SGLang’s pre-built image.\n",
    concurrency=32,
    allow_external_egress=False,
    shutdown_after_seconds=300,
    max_instances=1,
    scaling_threshold=0.75,
    engine_args={"trust_remote_code": True, "context_length": 8192},
)
