# -*- coding: utf-8 -*-
# Generated by chutes-ai-manager. Re-run `python cli.py generate ...` after YAML edits.

"""
Auto-generated vLLM chute (prebuilt-vllm) — Chutes pre-built image.
HF model: mistralai/Mistral-7B-Instruct-v0.3
Edit configs/prebuilt-vllm.yaml and re-run generate.
Docs: https://chutes.ai/docs/sdk-reference/templates
"""
from chutes.chute import NodeSelector
from chutes.chute.template import build_vllm_chute

chute = build_vllm_chute(
    username="your_username",
    model_name="mistralai/Mistral-7B-Instruct-v0.3",
    node_selector=NodeSelector(gpu_count=1, min_vram_gb_per_gpu=24),
    tagline="vLLM — OpenAI-compatible LLM serving",
    readme="# vLLM on Chutes (pre-built image)\n\nUses `build_vllm_chute` and Chutes-managed images. Endpoints include `/v1/chat/completions`.\nSee https://chutes.ai/docs/guides/templates\n",
    concurrency=64,
    allow_external_egress=False,
    shutdown_after_seconds=300,
    max_instances=1,
    scaling_threshold=0.75,
)
