# -*- coding: utf-8 -*-
# Generated by chutes-ai-manager. Re-run `python cli.py generate prebuilt-vllm-phi` after YAML edits.

"""
Auto-generated vLLM chute (prebuilt-vllm-phi) — Chutes pre-built image.
HF model: microsoft/Phi-3-mini-4k-instruct
"""
from chutes.chute import NodeSelector
from chutes.chute.template import build_vllm_chute

chute = build_vllm_chute(
    username="your_username",
    model_name="microsoft/Phi-3-mini-4k-instruct",
    node_selector=NodeSelector(gpu_count=1, min_vram_gb_per_gpu=16),
    tagline="vLLM — Phi-3 Mini (lighter GPU)",
    readme="# vLLM · Microsoft Phi-3 Mini\n\nSmaller model for tighter VRAM. Chutes pre-built vLLM image.\n",
    concurrency=32,
    allow_external_egress=False,
    shutdown_after_seconds=300,
    max_instances=1,
    scaling_threshold=0.75,
    engine_args={"trust_remote_code": True, "max_model_len": 4096},
)
