# -*- coding: utf-8 -*-
# Generated by chutes-ai-manager. Re-run `python cli.py generate ...` after YAML edits.

"""
Auto-generated embedding chute (prebuilt-embedding) — Chutes pre-built image.
HF model: BAAI/bge-small-en-v1.5
Edit configs/prebuilt-embedding.yaml and re-run generate.
Docs: https://chutes.ai/docs/sdk-reference/templates
"""
from chutes.chute import NodeSelector
from chutes.chute.template.embedding import build_embedding_chute

chute = build_embedding_chute(
    username="your_username",
    model_name="BAAI/bge-small-en-v1.5",
    node_selector=NodeSelector(gpu_count=1, min_vram_gb_per_gpu=16),
    tagline="Embeddings — text vectors",
    readme="# Embeddings on Chutes (pre-built image)\n\nUses `build_embedding_chute`. Endpoint: `POST /v1/embeddings`.\nSee https://chutes.ai/docs/sdk-reference/templates\n",
    concurrency=32,
    allow_external_egress=False,
    shutdown_after_seconds=300,
    max_instances=1,
    scaling_threshold=0.75,
    pooling_type="auto",
    max_embed_len=3072000,
    enable_chunked_processing=True,
)
