# -*- coding: utf-8 -*-
# Generated by chutes-ai-manager. Re-run `python cli.py generate ...` after YAML edits.

"""
Auto-generated video scaffold (video).
Implement cords for the API paths in your YAML (see Chutes custom templates).
"""
from pydantic import BaseModel, Field

from chutes.image import Image

image = (
    Image(
        username='your_username',
        name='video',
        tag='1.0.0',
        readme='Video generation',
    )
    .from_base('nvidia/cuda:12.1-runtime-ubuntu22.04')
    .set_user("root")
    .run_command('apt-get update && apt-get install -y git curl ffmpeg && rm -rf /var/lib/apt/lists/*')
    .with_python('3.11')

    .run_command("""
        pip install --no-cache-dir torch torchvision torchaudio \
        --index-url https://download.pytorch.org/whl/cu121
    """)

    .run_command("""
        pip install --no-cache-dir \
        torch \
        transformers \
        accelerate
    """)
    .with_env('HF_HOME', '/app/models')
    .run_command("mkdir -p /app/models")
    .set_workdir("/app")
    .set_user("chutes")
)


from chutes.chute import Chute, NodeSelector

chute = Chute(
    username='your_username',
    name='video',
    tagline='Video generation',
    readme='# Video generation\n\nScaffold for hosted video models (text-to-video, image-to-video). Wire your inference stack and dependencies in the generated module.\n\nSee the Chutes example: https://chutes.ai/docs/examples/video-generation\n',
    image=image,
    node_selector=NodeSelector(gpu_count=1, min_vram_gb_per_gpu=24, include=['rtx4090', 'a100']),
    concurrency=1,
    allow_external_egress=True,
    shutdown_after_seconds=300,
)



class EchoBody(BaseModel):
    message: str = Field(default="hello")


@chute.cord(
    public_api_path="/echo",
    public_api_method="POST",
    output_content_type="application/json",
)
async def echo(self, data: EchoBody) -> dict:
    return {"echo": data.message}


@chute.cord(
    public_api_path="/health",
    public_api_method="GET",
    output_content_type="application/json",
)
async def health(self) -> dict:
    return {"status": "ok", "chute_type": "video"}
